### ISSUE TITLE
Displaying only official name?

### ISSUE THREAD

**Issue by youngpixel** [mrmarkfrench/country-select-js#12]
Hi guys,

Thanks for the great plugin!
But Is there an easy way to display only official names of the country? 

Thanks

**Comment by mrmarkfrench** [comment]
There's not currently an easy way to do this, because the name of the country is a single field in the data with both the English and the local language version as a single string. I think that support for showing only one or the other makes sense, and I'd be happy to accept a pull request if you'd like to take the time to figure out how to make that happen.

It might also make it easier to let folks type the name of the country in either English or the local language and do a better job matching the country name as they type, even in cases where you still displayed both names.

**Comment by ArjunDhar** [comment]
Well how about an instance setting (JSON attribute), if true will apply a simple String filter method over the full name and remove anything in (.....) including the brackets.

This way in Display only the names are appearing without their locales, however because the core data model contains that intact, searching is not impacted, and no bloating of model (no need to add additional fields etc). 

Another option could be: Rather than the instance option being a BOOLEAN type. Use a callback function, where the user is free to implement their own Name formatting method. That can open a lot of possibilities actually,

Worth considering.

**Comment by mrmarkfrench** [comment]
I'd be more than happy to see a pull request that implements this.

**Comment by mrmarkfrench** [comment]
The latest version (v2.1.0) now allows you to set the localized name of a country (see the `localizedCountries` option, documented on the README). This will allow you to override the names of countries you wish to change.
