### ISSUE TITLE
Can you user the same image flags file from the plugin

### ISSUE THREAD

**Issue by oliveiraped** [mrmarkfrench/country-select-js#15]
Can you user the same image flags file from the plugin

https://github.com/Bluefieldscom/intl-tel-input

Please check this issue about retina display
https://github.com/Bluefieldscom/intl-tel-input/issues/299

**Comment by mrmarkfrench** [comment]
I will take a look at what would be required to update to use the newer flag images adopted by the plugin this one is based on.

I suspect it will be very possible, though time-consuming, to update to the newer image and adjust the CSS to match accordingly. This should give this plugin a better set of flags for use on a retina display.

However, I think it unlikely that we'll be able to let you easily load only a single image file for both plugins. Although many people (including myself) use both plugins, they are each designed to work on their own, and neither should require the other be installed in order to work. The side-effect is that each needs to provide its own image file. This also prevents changes to the image file used in one plugin breaking the display of flags in the other.

**Comment by humrochagf** [comment]
i also fixed this issue, but is on a branch of my fork, after finishing with the #33 pr i will make another to fix that
