### ISSUE TITLE
When the counrty is set through the text field, the flag is updated but not the xx_code field

### ISSUE THREAD

**Issue by zorbalaras** [mrmarkfrench/country-select-js#2]
Adding "this.countryCodeInput.val(countryCodes[0]);" line 350 seems to fix the issue. Or Am I missing something here?

**Comment by mrmarkfrench** [comment]
Nope, you're correct. I hadn't noticed the issue because while I use this library in my own projects every day, I usually add a "readonly" on the country name field and expect users to select their country using the flag drop-down.

I've fixed it now (using your suggested modification), and you should be all set.

**Comment by zorbalaras** [comment]
Great, thanks a lot for the fast code update. By the way, the .min.js should also need an update, right?

**Comment by mrmarkfrench** [comment]
Huh. My usual process to automatically update the minified version when the regular version changes didn't work. Thanks for noticing. I've updated it now.
