### ISSUE TITLE
Does not work in latest jquery version

### ISSUE THREAD

**Issue by maxpen** [mrmarkfrench/country-select-js#21]
It breaks from version 2.1.4 and upwards.

**Comment by mrmarkfrench** [comment]
Any information as to why? What breaks? Do you see an error message? Does it not display correctly?
Please help us nail this down by providing as much information as possible about the problem.

**Comment by master412160** [comment]
It simply doesn't display. Have you tried it out on the latest versions of jquery? 

Sorry for the delay of not replying sooner I am just now clearing my inbox and found an e-mail about this topic.

**Comment by wadie** [comment]
Any update on this ? Doesn't work on latest jQuery.

**Comment by wadie** [comment]
There are no error messages whatsoever,simply when I include the latest jQuery nothing happens. normal input form. when I load earlier version (1.11.1) it works flawlessly !

**Comment by bwydoogh** [comment]
I believe this may be related to the use of the `load` function, which is used **by the latest  `1.1.0` version of this plug-in**: see http://stackoverflow.com/questions/38871753/uncaught-typeerror-a-indexof-is-not-a-function-error-when-opening-new-foundat. The use of `load` is deprecated since JQuery 3.x, but still used in the `countrySelect.js` file. I see it is fixed on the master branch (22 August 2016), so I guess we just need a new release, no :simple_smile:?

Notice the error shown in the Chrome Developer Tools

`Uncaught TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (jquery.min.js:4)
    at countrySelect.js:32
    at countrySelect.js:8
    at countrySelect.js:10
r.fn.load @ jquery.min.js:4
(anonymous) @ countrySelect.js:32
(anonymous) @ countrySelect.js:8
(anonymous) @ countrySelect.js:10
`

**Comment by ilibilibom** [comment]
With latest jQuery version - this error is generated in console:   
Uncaught TypeError: a.indexOf is not a function at r.fn.init.r.fn.load (jquery.min.js:4) at countrySelect.js:32 at countrySelect.js:8 at countrySelect.js:10 r.fn.load @ jquery.min.js:4 (anonymous) @ countrySelect.js:32 (anonymous) @ countrySelect.js:8 (anonymous) @ countrySelect.js:10

**Comment by diimpp** [comment]
Same `TypeError: $(...).countrySelect is not a function` error with jquery 3.2.1

```
jQuery.Deferred exception: $(...).countrySelect is not a function @http://url:95:17
j@https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29997
g/</k<@https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313
 undefined
```

**Comment by mrmarkfrench** [comment]
Based on the comments from @bwydoogh and my own testing, it looks like this issue was fixed in master but the Bower file hadn't been updated to reflect the newer version of the plugin available.

Pull request #59 resolved this issue. I am able to confirm correct functionality with jQuery version 2.x and 3.x (along with continued functionality with 1.x). A simple update to the latest version should fix your issue.
