### ISSUE TITLE
Multilanguage countries should show all their names

### ISSUE THREAD

**Issue by cnsgithub** [mrmarkfrench/country-select-js#26]
I don't know if this is the only case but for countries where languages coexist with same legal status (and not just by majority of speakers) it would be reasonable to use the all language names for them

Example:

Switzerland (Schweiz/Suisse/Svizzera)
instead of Switzerland (Schweiz)

**Comment by mrmarkfrench** [comment]
The system is configured the way it is, with only the majority local language, because that was the dataset I was working from. If you have a data set that includes all of the languages, I'd be happy to take a look at it, but I think the result is going to be unworkable in some cases. Zimbabwe, for example, recognizes 16 official languages. The resulting string is going to be too long to display on any but the largest devices, and make the input look really strange.

**Comment by mrmarkfrench** [comment]
The latest version (v2.1.0) now allows you to set the localized name of a country (see the `localizedCountries` option, documented on the README). This will allow you to override the names of countries you wish to change.

As such, if you require the names of countries specified with additional languages or options, this is now possible for you to specify.
