### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^a\/: \ at end of pattern

### ISSUE THREAD

**Issue by cnsgithub** [mrmarkfrench/country-select-js#27]
When typing '\' there will be a uncaught syntax error. Probably not critical, still it would be good to handle it

**Comment by mrmarkfrench** [comment]
My reading of this is that you saw this error when typing the empty string into the input box? That is, when deleting the content of the box and then blurring the input? If I understand this correctly, this issue is resolved in the current version of the plugin. I'm going to close this issue, but if I have misunderstood what the problem was, and you're still able to duplicate it, please let me know.
