### ISSUE TITLE
how to make it send country code rather than country-name?

### ISSUE THREAD

**Issue by shivabhusal** [mrmarkfrench/country-select-js#39]
I was wondering if there is any way to make it select country code rather than country name. Can anyone help me?

now it sends data to server like `"country_code"=>"Albania (Shqipëri)"`

**Comment by brianwong3** [comment]
you will need to run 'getSelectedCountryData' and get the iso2 name before submitting.

at least thats what i do, and if my page fails due to validation issues, i usually just run 'selectCountry' and pass in the iso2 name to reselect the country again

**Comment by mrmarkfrench** [comment]
If I understand the question correctly, you're suggesting that you don't get the country code, you get the name of the country? Do you get the same value passed in `country` as you get in `country_code`? I just tried this myself and wasn't able to duplicate the issue.

**Comment by mrmarkfrench** [comment]
Haven't seen any further action on this. In case there was a misunderstanding, can you also confirm that you are using the `_code` suffix to a field so that you have two inputs, one for the country and one for the country code?

See the example in point number 4 under "Getting Started" on the README for this plugin.

**Comment by jhio1** [comment]
Hello!
When i tried to pass the country_code as a parameter , I always get a null value from it.

Any advise?

**Comment by mrmarkfrench** [comment]
So, @jhio1, I'm not sure what you mean about a parameter. Did you create an `input` element with the ID `country_code`, and you had an input element with the ID `country` which you applied the plugin to? Or were you trying to pass `country_code` as a parameter in the object you pass to the plugin when you initialize it?

**Comment by mrmarkfrench** [comment]
Having seen no further response on this issue, and given that it's working correctly in my own tests and for other users, I'm going to assume that the problem was a misunderstanding about how to use the country code feature. I'm closing this issue, but if you are able to replicate the problem please re-open it or file a new one so we can take a look.
