### ISSUE TITLE
Issue on page reload

### ISSUE THREAD

**Issue by NuriddinK** [mrmarkfrench/country-select-js#53]
There seem to be an error when using the CountrySelect plugin.

`jQuery.Deferred exception: n is undefined`
`TypeError: n is undefined`

The issue occurs on page reload button click only.

(Jquery 3.1.1 & Mozilla 58)

**Comment by Nohossat** [comment]
Hi, 

I have the same issue

**Comment by mrmarkfrench** [comment]
Any further insight on this? Does it matter if the refresh is or is not a hard refresh? Does the error occur only with JQuery 3.1.1 or with any supported version?

**Comment by mrmarkfrench** [comment]
With further testing, I'm not able to duplicate this issue in jQuery 1.x, 2.x, or 3.x, using either the latest version of Chrome or Firefox. There was previously an issue running the plugin with newer versions of jQuery, which has since been resolved.

I'm going to close this issue, but if you are still able to replicate the problem, please let me know.
