### ISSUE TITLE
How to display the flag which user chose？

### ISSUE THREAD

**Issue by punchan36** [mrmarkfrench/country-select-js#78]
Thank you for publishing such an useful plugin.

I put this select box on user's profile edit page (`edit.html.erb`), and displayed its country's name on user's profile page (`show_html.erb`)

**`edit.html.erb`**

      <input type="text" name="country" id="country" value="<%= @user.country %>">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <%= javascript_include_tag "/country-select-js-master/build/js/countrySelect.min.js" %>

**`show.html.erb`**

      <%= @user.country %>
      # it shows country's name such as "United States".

Is it possible to display its country's flag too?

**Comment by mrmarkfrench** [comment]
There's not a super simple way to get it to return just the flag you want. Maybe the easiest way to do what you're looking for is to display a country select box, and to limit it to show only their current country.

So if they had selected the United States, as in your example, you could do something like this:
```
$("#country").countrySelect({
  defaultCountry: 'us',
  onlyCountries: ['us']
});
```
...which would show both the country name and the flag, but not let them edit it (because letting them change it would give them the impression that they were updating their settings, when it's really just for display purposes).

**Comment by punchan36** [comment]
Thank you very much for your comment!

So, it basically means that flag icon can be displayed only in a select box?
Is it probably impossible to display both of the countries' name and flag simply without a select box?

**Comment by mrmarkfrench** [comment]
The issue is that there isn't a tiny flag picture to give you. The flags are all part of a single image and it uses a combination of javascript and CSS to make only the part of the larger image that contains the flag for the selected country appear. As a result, there's no easy way to just give you the flag. It's possible that you could hook into the methods that do the javascript part, but even then you'd need to make the element you wanted to contain the flag picture have compatible classes, sizes, margins, etc, in order for it to display properly.

There just really doesn't exist a simple "call function, get flag" solution to your problem here.

**Comment by punchan36** [comment]
I understand it. Thank you very much for taking your time! :)
